### PR TITLE
using the bottommost axes as the last axes instance

### PR DESCRIPTION
**Pull request by K20shores**
This allows issue #60 to to be resolved. I am unaware of the consequences of this, though.

### CODE REVIEW

**Comment by K20shores** [comment]
This is the image generated with the same code in #60 using the patch I submitted in this PR, for your reference (with some added styling of the right hand figure).

image

**Comment by K20shores** [comment]
Two of the tests in the python notebook fail:

1. The first one that shows the grid. The bottom grid is drawn correctly, but the grids above that are drawn on top of the data. I am working on that
2. The Unknown Pleasures album cover is not being displayed. I am not sure why. I will look into that after I figure out the grid. 


If you happen to want to accept this as a PR and have any insight, please let me know.

**Comment by leotac** [comment]
Hey! Thanks for the contribution. I'll take a look when I have the chance.

**Comment by K20shores** [comment]
There are still some outlying problems:

1. The Unknown Pleasures example, for some reason, is not rendering in the notebook for me.
2. Grid lines in density estimate plots overlay the density estimate. That is not true for histograms.

I am looking into both.

**Comment by K20shores** [comment]
Well, I figured out the Unknown Pleasures issue, all that's left is the grid zorder issue.

**Pull request closed without merging**
